version=${project.version}
buildtime=${timestamp}
builder=${env.USERNAME}
builderName=${avoidlock.build.user.name}
builderEmail=${avoidlock.build.user.email}
buildhost=${env.COMPUTERNAME}
buildOs=${os.name}
gitBranch=${avoidlock.branch}
gitCommitIdDescribe=${avoidlock.commit.id.describe}
gitCommitId=${avoidlock.commit.id.full}
gitCommitUrl=${avoidlock.remote.origin.url}
gitCommitTime=${avoidlock.commit.time}
gitDirty=${avoidlock.dirty}
